blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',
         views.post_list,
         name='post_list'), #root
    path('about/',
         views.about,
         name='about'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('post/new/',
         views.post_new,
         name='post_new'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/edit/',
         views.post_edit,
         name='post_edit'),
    path('<int:post_id>/share/',
         views.post_share,
         name='post_share'),
    path('tag/<slug:tag_slug>/',
         views.post_list,
         name='post_list_by_tag'),
    ]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap,}

urlpatterns = [
    path('',
         include('blog.urls', namespace = '')),
    path('admin/',
         admin.site.urls),
    path('blog/',
         include('blog.urls',namespace = 'blog')),
    path('sitemap.xml',
         sitemap,
         {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor/',
         include('ckeditor_uploader.urls')),
    path('search/',
         include('haystack.urls'))

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# Create your models here.

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset()\
               .filter(status='published').filter(published_date__lte=timezone.now())

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = RichTextUploadingField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    slug = models.SlugField(max_length=250,
                            unique_for_date='published_date'
                            )
    tags = TaggableManager()

    objects = models.Manager()
    publishedobjects = PublishedManager()

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        )
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title) # Convert the title into a slug
        super(Post, self).save(*args, **kwargs)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.published_date.year,
                             self.published_date.month,
                             self.published_date.day,
                             self.slug]
                       )

    class Meta:
        ordering = ('-published_date',)

    def __str__(self):
        return self.title

class Comment(models.Model): #Not used in this version
    post    = models.ForeignKey   (Post,
                                   on_delete=models.CASCADE,
                                   related_name='comments')
    name    = models.CharField    (max_length=80)
    email   = models.EmailField   ()
    body    = RichTextUploadingField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active  = models.BooleanField (default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms

from .models import Comment, Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'status', 'tags')


class EmailPostForm(forms.Form):
    name     = forms.CharField (max_length=30)
    email    = forms.EmailField()
    to       = forms.EmailField()
    comments = forms.CharField (required=False,
                                widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.db import models
from django.db.models import Count
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from taggit.models import Tag
from .forms import CommentForm, EmailPostForm, PostForm
from .models import Comment, Post
from mysite.readcredentials import readcredentials

from haystack.query import SearchQuerySet

def post_list(request, tag_slug=None):
    object_list = Post.publishedobjects.order_by('published_date')
    search_term = ''

    tag = None
    if tag_slug:
        tag         = get_object_or_404 (Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    if 'search' in request.GET:
        search_term = request.GET['search']
        object_list = object_list.filter(text__icontains=search_term)

    paginator = Paginator(object_list, 5) # posts per page
    page = request.GET.get('page') # current page number
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    context = { 'page'       : page,
                'posts'      : posts,
                'tag'        : tag  ,
                'search_term': search_term}
    return render(request,
                  'blog/post_list.html',
                  context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             published_date__year=year,
                             published_date__month=month,
                             published_date__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None
    if request.method == 'POST': # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment        = comment_form.save(commit=False)
            new_comment.post   = post # Assign the current post to the comment
            new_comment.save()        # Save the comment to the database
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects .filter(status='published'
                                ).filter(tags__in=post_tags_ids
                                ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')
                                           ).order_by('-same_tags',
                                                      '-published_date')[:5]
    return render(request,
                  'blog/post_detail.html',
                  {'post'         : post,
                   'comments'     : comments,
                   'new_comment'  : new_comment,
                   'comment_form' : comment_form,
                   'similar_posts': similar_posts})


def post_edit(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             published_date__year=year,
                             published_date__month=month,
                             published_date__day=day)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post                = form.save(commit=False)
            post.author         = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return render(request,
                          'blog/post_detail.html',
                          {'post': post})
    else:
        form = PostForm(instance=post)
    return render(request,
                  'blog/post_edit.html',
                  {'form': form})


def post_new(request, year=timezone.now().year, month=timezone.now().month, day=timezone.now().day, post=""):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post                = form.save(commit=False)
            post.author         = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return render(request,
                          'blog/post_detail.html',
                          {'post': post})
    else:
        form = PostForm()
    return render(request,
                  'blog/post_edit.html',
                  {'form': form})


def post_share(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status='published')
    sent = False

    if request.method == 'POST': # Form submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cleaneddata = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = '{} ({}) recommends you reading "{}"'.format(cleaneddata['name'],
                                                                   cleaneddata['email'],
                                                                   post.title,)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title,
                                                                    post_url,
                                                                    cleaneddata['name'],
                                                                    cleaneddata['comments'],)
            send_mail(subject,
                      message,
                      readcredentials()[1],
                      [cleaneddata['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request,
                  'blog/post_share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent})


def about(request):
    return render(request,
                  'blog/about.html')


def search_titles(request):
    articles = SearchQuerySet().autocomplete(content_auto=request.POST.get('search_text',''))

    return render_to_response('search.html', {'articles' : articles})

blog/templates/blog/about.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <div class="row">

        <div class="col-sm-4 about-left">
          <h1>About me</h1>
          <div class="self-portrait">
            <img src="{% static 'images/jose-garban.jpg' %}" alt="José Garbán">
          </div>
        </div>

        <div class="col-sm-4">
            <div class="about-p">
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static %}

<html>
  <head>
    <title>José Garbán's blog</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}">
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
    <link rel="stylesheet" href="{% static "css/prism.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Arvo">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "js/prism.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

  </head>

  <header>
    <div class="header-left">
      <h1 ><a class="header-title" href="{% url 'blog:post_list'%}">José Garbán's blog</a> </h1>
    </div>
    <div class="header-right">
      <span><a href="{% url 'blog:about' %}" class="header-anchor">About me</a></span>
    </div>
  </header>

  <body>
    <div class="content-container">
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>

</html>

blog/templates/blog/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

blog/templates/blog/pagination.html
<div class="pagination">

    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.

        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>

</div>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block content %}

<div class="content-container">
  <br>
  <br>
  <div class="row">
    <div class="col-md-2 no-padding">
      <div class="date-container">
        {% if post.published_date %}
          <div class="date-inpost">
            {{ post.published_date }}
          </div>
        {% endif %}
      </div>
    </div>

    <div class="col-md-6">
      <article class="post">
        <h1 class="post-title">{{ post.title }}</h1>
        <p class="tags">Tags:
          {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
              {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>

        {% if user.is_authenticated %}
          <a class="btn btn-default" href="{{ post.get_absolute_url }}edit/">
            <span class="glyphicon glyphicon-pencil"> Edit post</span>
          </a>
        {% endif %}
        <br>
        <p>{{ post.text|safe }}</p>
        <br>
        <p>
          <a href="{% url "blog:post_share" post.id %}">Share this post via e-mail</a>
        </p>
      </article>

      <div class="comments">
        <div id="disqus_thread"></div>
        <script>

        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

        var disqus_config = function () {
          this.page.url = 'https://josegarban.pythonanywhere.com/blog/{{post.published_date.year}}/{{post.published_date.month}}/{{post.published_date.day}}/{{post.slug}}/';  // Replace PAGE_URL with your page's canonical URL variable
          this.page.identifier = '/{{post.published_date.year}}/{{post.published_date.month}}/{{post.published_date.day}}/{{post.slug}}/';
          this.page.title = "{{post.title}}";
        };

        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://josegarban.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

        <script id="dsq-count-scr" src="//josegarban.disqus.com/count.js" async></script>

      </div>

    </div>

    <div class="col-md-3">
      <aside class="similar">
        <h3>Similar posts</h3>
        {% for post in similar_posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
        {% empty %}
        <p>There are no similar posts yet.</p>
        {% endfor %}
      </aside>
    </div>
    <div class="col-md-1">
    </div>
  </div>
</div>

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Edit post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      {% if tag %}
        <h1>Posts tagged with "{{ tag }}"</h1>
      {% else %}
        <br>
      {% endif %}
    </div>
  </div>

    {% for post in posts %}

      <article class="post">
        <div class="row">
          <div class="col-md-2" "date-container">
            <div class="date-inlist">
              {{ post.published_date }}
            </div>
          </div>
          <div class="col-md-6">
            <h2><a href="{{ post.get_absolute_url }}" class="post-list-post-title" "post-title">{{ post.title }}</a></h2>
          </div>
          <div class="col-md-4">
            {% if forloop.first %}
            <h3>Search</h3>
            {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
          </div>
          <div class="col-md-6">
            <p class="tags">Tags:
              {% for tag in post.tags.all %}
              <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
              </a>
              {% if not forloop.last %}, {% endif %}
              {% endfor %}
            </p>
            <p>{{ post.text|truncatewords:30|safe }}</p>
          </div>
          <div class="col-md-4">
            {% if forloop.first %}
            <form class="form-inline my-2 my-lg-0">
              <input
              class="form-control mr-sm-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
              name = "search"
              value ="{{search_term}}">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% endif %}
          </div>
        </div>
      </article>
    {% endfor %}

  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      {% include "blog/pagination.html" with page=posts %}
      <br>
      {% if user.is_authenticated %}
      <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"> New post</span></a>
      {% endif %}
    </div>
  </div>
{% endblock %}

blog/templates/blog/post_share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
          {% for field in form %}
              <div>
                  {{ field.errors }}
                  <p>{{ field.label_tag }}</p>
                  <p>{{ field }}</p>
              </div>
          {% endfor %}
        {% csrf_token %}
        <p> </p>
        <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}